//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyDealTask.DependencyResolver;
using MyDealTask.Contracts;
using System.ComponentModel.Composition;
namespace MyDealTask.DataAccess
{
    	[Export(typeof(IComponent))]
        public class DependencyResolver : IComponent
        {
            public void SetUp(IRegisterComponent registerComponent)
            {
    				registerComponent.RegisterType<IPassengerRecordRepository, PassengerRecordRepository>();
    				registerComponent.RegisterType<IPNLFileRepository, PNLFileRepository>();
    				registerComponent.RegisterType<IRecordLocatorRepository, RecordLocatorRepository>();
    			}
        }
}
