//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDealTask.DataAccess
{
    using System;
    using MyDealTask.DataModel;
    using MyDealTask.Model;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    
    public partial class PassengerRecordRepository : BaseRepository<PassengerRecord> 
    {
    	public PassengerRecordRepository(){}
    }
}
