//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDealTask.DataAccess
{
    using System;
    using MyDealTask.Contracts;
    using MyDealTask.Model;
    
    public partial class RecordLocatorRepository : BaseRepository<RecordLocator>, IRecordLocatorRepository 
    {
    	public RecordLocatorRepository(){}
    }
}
