CREATE TABLE [dbo].[RecordLocator]
(
	[Id] INT  NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[PNLFileId] INT NOT NULL FOREIGN KEY REFERENCES PNLFile(Id), 
    [Code] NCHAR(6) NOT NULL,
	CONSTRAINT [UQ_PNLFIELD_CODE] UNIQUE NONCLUSTERED
    (
        [PNLFileId], [Code]
    )
)
