CREATE TABLE [dbo].[RecordLocator] (
    [Id]        INT       IDENTITY (1, 1) NOT NULL,
    [PNLFileId] INT       NOT NULL,
    [Code]      NCHAR (6) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__RecordLoc__PNLFi__21B6055D] FOREIGN KEY ([PNLFileId]) REFERENCES [dbo].[PNLFile] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [UQ_PNLFIELD_CODE] UNIQUE NONCLUSTERED ([PNLFileId] ASC, [Code] ASC)
);


